name: Heroku Review Application
description: >-
  Create a Heroku review app when a PR is raised by someone with write or admin
  access
runs:
  using: node12
  main: dist/index.js
branding:
  icon: book-open
  color: orange
